// Mocks generated by Mockito 5.4.6 from annotations
// in tellulu/test/features/create/character_creation_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:tellulu/services/gemini_service.dart' as _i2;
import 'package:tellulu/services/stability_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i2.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i4.Future<String?> generateCharacterDescription({
    required String? prompt,
    String? visualContext,
    String? model = 'gemini-2.0-flash',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateCharacterDescription, [], {
              #prompt: prompt,
              #visualContext: visualContext,
              #model: model,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> analyzeImage(_i5.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImage, [imageBytes]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> verifyModelHealth(String? model) =>
      (super.noSuchMethod(
            Invocation.method(#verifyModelHealth, [model]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> distillVisualTags(String? analysis) =>
      (super.noSuchMethod(
            Invocation.method(#distillVisualTags, [analysis]),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(#distillVisualTags, [analysis]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> enhanceCharacterDescription(
    String? name,
    String? rawDescription, {
    String? context,
    String? visualDNA,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #enhanceCharacterDescription,
              [name, rawDescription],
              {#context: context, #visualDNA: visualDNA},
            ),
            returnValue: _i4.Future<String>.value(
              _i3.dummyValue<String>(
                this,
                Invocation.method(
                  #enhanceCharacterDescription,
                  [name, rawDescription],
                  {#context: context, #visualDNA: visualDNA},
                ),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<Map<String, String>> generateStyleProfile(String? vibeName) =>
      (super.noSuchMethod(
            Invocation.method(#generateStyleProfile, [vibeName]),
            returnValue: _i4.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i4.Future<Map<String, String>>);

  @override
  _i4.Future<Map<String, dynamic>?> generateStory({
    required List<Map<String, String>>? castDetails,
    required String? vibe,
    required String? readingLevel,
    required String? specialTouch,
    String? model = 'gemini-2.0-flash',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateStory, [], {
              #castDetails: castDetails,
              #vibe: vibe,
              #readingLevel: readingLevel,
              #specialTouch: specialTouch,
              #model: model,
            }),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<Map<String, dynamic>?> validateImageSafety(
    _i5.Uint8List? imageBytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#validateImageSafety, [imageBytes]),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);
}

/// A class which mocks [StabilityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStabilityService extends _i1.Mock implements _i6.StabilityService {
  MockStabilityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i4.Future<String?> generateImage({
    required String? prompt,
    required String? modelId,
    _i5.Uint8List? initImageBytes,
    String? stylePreset,
    double? imageStrength = 0.35,
    double? cfgScale,
    int? seed,
    String? negativePrompt,
    List<Map<String, dynamic>>? weightedPrompts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateImage, [], {
              #prompt: prompt,
              #modelId: modelId,
              #initImageBytes: initImageBytes,
              #stylePreset: stylePreset,
              #imageStrength: imageStrength,
              #cfgScale: cfgScale,
              #seed: seed,
              #negativePrompt: negativePrompt,
              #weightedPrompts: weightedPrompts,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<bool> verifyModelHealth(String? modelId) =>
      (super.noSuchMethod(
            Invocation.method(#verifyModelHealth, [modelId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
