// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCchYFnTdtMMUGxj94oIPPW2XLQijN6oBY',
    appId: '1:608345659362:web:03034f8e2f048850904bbb',
    messagingSenderId: '608345659362',
    projectId: 'tellulu',
    authDomain: 'tellulu.web.app',
    storageBucket: 'tellulu.firebasestorage.app',
    measurementId: 'G-ZBQCC9JF9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5u37Pjn3A3RLr4fYkHtGMx3DAk_TG3ck',
    appId: '1:608345659362:android:73b460ed6f30d466904bbb',
    messagingSenderId: '608345659362',
    projectId: 'tellulu',
    storageBucket: 'tellulu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClv-pjqrXrJPyDI_QanxdTXg64DRNRsbQ',
    appId: '1:608345659362:ios:af43fba0578673e4904bbb',
    messagingSenderId: '608345659362',
    projectId: 'tellulu',
    storageBucket: 'tellulu.firebasestorage.app',
    androidClientId: '608345659362-hcfhbous04mj91hfopaq6lkud3edvn59.apps.googleusercontent.com',
    iosClientId: '608345659362-ubl0lvdpnfh2fg7hs3c4mooa7ab09ulg.apps.googleusercontent.com',
    iosBundleId: 'com.tellulu.tellulu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClv-pjqrXrJPyDI_QanxdTXg64DRNRsbQ',
    appId: '1:608345659362:ios:af43fba0578673e4904bbb',
    messagingSenderId: '608345659362',
    projectId: 'tellulu',
    storageBucket: 'tellulu.firebasestorage.app',
    androidClientId: '608345659362-hcfhbous04mj91hfopaq6lkud3edvn59.apps.googleusercontent.com',
    iosClientId: '608345659362-ubl0lvdpnfh2fg7hs3c4mooa7ab09ulg.apps.googleusercontent.com',
    iosBundleId: 'com.tellulu.tellulu',
  );

}